### ISSUE TITLE
Boundaries bug on this pin 19161000028001

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/website#380]
http://localhost/address.php?pin=19161000028001

````
PHP Fatal error:  Uncaught PDOException: SQLSTATE[XX000]: Internal error: 7 ERROR:  Error performing intersection: TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1145406.7002703433 1864112.7327952816 at 1145406.7002703433 1864112.7327952816 in 
[snipped]
#3 /Users/stevevance/Sites/Chicago Cityscape/classes/BoundariesGetter.php(37): BoundariesGetter->fetchBoundaries()
#4 /Users/stevevance/Sites/Chicago Cityscape/php/class.address.php(644): BoundariesGetter->getBoundaries()
[snipped]
````

**Comment by stevevance** [comment]
First, this no longer causes a fatal error and for the page to be blank. 

Also, we had to fix some TIF districts in Kane and Will Counties, and in Rockford, because they had invalid geometry.

**Comment by stevevance** [comment]
It turns out that this is a problem with the Parcel/PIN's geometry!
